from flask import render_template 
from app_context import app, json 

@app.route('/', defaults={'meta_desc': 'Your Science. Our Tools. Fast Results.'})
@app.route('/404.html')
@app.route('/design_guide', defaults={'meta_desc': 'A step-by-step guide to designing your study.'})
@app.route('/tools/', defaults={'meta_desc': 'MySampleSize Tools: calculate sample size, statistical power, and simulate a study'})
@app.route('/tools/sample_size', defaults={'meta_desc': 'Calculate your sample size with this easy-to-use interface.'})
@app.route('/tools/power_size', defaults={'meta_desc': 'Calculate your statistical power based on a given sample size.'})
@app.route('/tools/power_graph', defaults={'meta_desc': 'Explore the tradeoff between power and sample size.'})
@app.route('/tools/rng', defaults={'meta_desc': 'Random number generator for blocking your experimental design'})
@app.route('/tools/analysis', defaults={'meta_desc': 'Data analysis'})
@app.route('/tools/simulations', defaults={'meta_desc': 'Simulate outcomes of your study.'})
@app.route('/tools/report', defaults={'meta_desc': 'Generate a report of our power and sample size calculations to submit for your proposal'})
@app.route('/auth/home')
@app.route('/auth/signup')
@app.route('/auth/logout.html')
@app.route('/account/')
@app.route('/account/billing')
@app.route('/account/update')
@app.route('/account/projects')
@app.route('/report/')
@app.route('/report/supplement')
@app.route('/report/checklist')
@app.route('/report/userprojects')
@app.route('/report/power')
@app.route('/help/', defaults={'meta_desc': 'Help on statistical basics, different types of tests, and case studies to use with our tools.'})
@app.route('/help/faq')
@app.route('/help/glossary')
@app.route('/help/casestudies', defaults={'meta_desc': 'Real case studies to explore our tools with.'})
@app.route('/help/contact_us', defaults={'meta_desc': 'Need help or more information? Contact us!'})
@app.route('/help/designtypes', defaults={'meta_desc': 'Explore different design types (e.g. randomized, blocked, crossover)'})
@app.route('/help/tutorial/', defaults={'meta_desc': 'Tutorial Home'})
@app.route('/help/tutorial/overview', defaults={'meta_desc': 'Tutorial - Overview'})
@app.route('/help/tutorial/designguide', defaults={'meta_desc': 'Tutorial - Design Guide'})
@app.route('/help/tutorial/tools', defaults={'meta_desc': 'Tutorial - Tools'})
@app.route('/help/tutorial/reports', defaults={'meta_desc': 'Tutorial - Reports'})
@app.route('/help/stattests/', defaults={'meta_desc': 'Statistical Tests'})
@app.route('/help/stattests/overview', defaults={'meta_desc': 'Statistical Tests - Overview'})
@app.route('/help/stattests/significance', defaults={'meta_desc': 'Statistical Tests - Significance and Power'})
@app.route('/help/stattests/mean_std_es', defaults={'meta_desc': 'Statistical Tests - Mean, Standard Deviation, and Effect Size'})
@app.route('/help/stattests/ttest_def', defaults={'meta_desc': 'Statistical Tests - Definitions'})
@app.route('/help/stattests/t1', defaults={'meta_desc': 'Statistical Tests - One-Sample T-Test'})
@app.route('/help/stattests/t2', defaults={'meta_desc': 'Statistical Tests - Paired T-Test'})
@app.route('/help/stattests/tI', defaults={'meta_desc': 'Statistical Tests - Independent-Sample T-Test'})
@app.route('/help/stattests/anova_def', defaults={'meta_desc': 'Statistical Tests - Definitions'})
@app.route('/help/stattests/anova', defaults={'meta_desc': 'Statistical Tests - ANOVA'})
@app.route('/help/stattests/2anova', defaults={'meta_desc': 'Statistical Tests - 2-Way ANOVA'})
@app.route('/help/stattests/3anova', defaults={'meta_desc': 'Statistical Tests - 3-Way ANOVA'})
@app.route('/help/stattests/anova_rep', defaults={'meta_desc': 'Statistical Tests - Repeated Measures ANOVA'})
@app.route('/help/statbasics/', defaults={'meta_desc': 'Statistical Basics'})
@app.route('/help/statbasics/overview', defaults={'meta_desc': 'Statistical Basics - Overview'})
@app.route('/standalone/overview')
@app.route('/help/statbasics/significance', defaults={'meta_desc': 'Statistical Basics - Significance'})
@app.route('/standalone/significance')
@app.route('/help/statbasics/stdev', defaults={'meta_desc': 'Statistical Basics - Standard Deviation'})
@app.route('/standalone/stdev')
@app.route('/help/statbasics/groups', defaults={'meta_desc': 'Statistical Basics - Groups and Factors'})
@app.route('/standalone/groups')
@app.route('/help/statbasics/samplesize', defaults={'meta_desc': 'Statistical Basics - Sample Size'})
@app.route('/standalone/samplesize')
@app.route('/help/statbasics/effect', defaults={'meta_desc': 'Statistical Basics - Effect Size'})
@app.route('/standalone/effect')
@app.route('/help/statbasics/power', defaults={'meta_desc': 'Statistical Basics - power'})
@app.route('/standalone/power')
@app.route('/help/statbasics/effect_anova', defaults={'meta_desc': 'Statistical Basics - Effect Size in ANOVA'})
@app.route('/standalone/effect_anova')
@app.route('/help/statbasics/effect_cohen', defaults={'meta_desc': 'Statistical Basics - Cohen`s d and f Values'})
@app.route('/standalone/effect_cohen')
def index_js_route(meta_desc=None): 
    import sys 
    
    json_data = [0,0]
    with open('static/module_tools/tools_labels_power.json') as json_file:
        json_data[0] = json.load(json_file)
    with open('static/module_tools/tools_labels_sample.json') as json_file:
        json_data[1] = json.load(json_file)
    
    return render_template('index.html', os_type=sys.platform, json_data=json_data, meta_desc=meta_desc) 

