shinyUI(fluidPage(

  titlePanel("Compute Power and Simulate a Three-Factor Comparison Experiment"),

  sidebarLayout(
    sidebarPanel(
      p("Enter parameters below and press Compute Power"),
      numericInput("n",label="Number animals per group",value = 10),
      numericInput("pM",label="Number levels in Main Factor",value = 2),
      numericInput("pS",label="Number levels in 2nd Factor",value = 2),
      numericInput("pT",label="Number levels in 3rd Factor",value = 2),
	  numericInput("cMean",label="Mean response of control group",value = 1),
      numericInput("deltaM",label="Main Factor Effect Size",value = 10,step=0.001),
      numericInput("deltaS",label="2nd Factor Effect Size",value = 1,step=0.001),
      numericInput("deltaT",label="3rd Factor Effect Size",value = 0.5,step=0.001),
      numericInput("deltaMS",label="Main-2nd Factor Effect Size",value = 10,step=0.001),
      numericInput("deltaMT",label="Main-3rd Factor Effect Size",value = 1,step=0.001),
      numericInput("deltaST",label="2nd-3rd Interaction Effect Size",value = 0.5,step=0.001),
      numericInput("deltaMST",label="Three-way Interaction Effect Size",value = 0.1,step=0.001),
	  numericInput("sigma",label="Standard Deviation",value = 1,step=0.001),
      numericInput("alpha",label="Significance",value = 0.05,step=0.001),
      actionButton("getPower",label="Compute power"),
      p(" "),
      h4(textOutput("powerTextM")),
      p(" "),
      h4(textOutput("powerTextS")),
      p(" "),
      h4(textOutput("powerTextT")),
      p(" "),
      h4(textOutput("powerTextMS")),
      p(" "),
      h4(textOutput("powerTextMT")),
      p(" "),
      h4(textOutput("powerTextST")),
      p(" "),
      h4(textOutput("powerTextMST")),
      p(" ")
	  ),

    mainPanel(
    p("After computing power, simulate an experiment with the parameters you have chosen"),
    p("How do you think the main factor impacts your outcome?  Will it increase, decrease, go down and up, or go up and then down? Select one"),
    selectInput("shape",label="Select response shape",c("Increasing" = "linearUp",
                  "Decreasing" = "linearDown"),selected="linearUp"), 
    p("How do you think the secondary factor impacts your outcome?  Will it increase, decrease, go down and up, or go up and then down? Select one"),
    selectInput("shape2",label="Select response shape",c("Increasing" = "linearUp",
                  "Decreasing" = "linearDown"),selected="linearUp"), 
    p("Do the main and second factors work together or in opposition?"),
    selectInput("shape12",label="Select interaction type",c("Cooperative" = "coop",
                  "Opposing" = "oppo"),selected="coop"), 
    p("How do you think the 3rd factor impacts your outcome?  Will it increase, decrease, go down and up, or go up and then down? Select one"),
    selectInput("shape3",label="Select response shape",c("Increasing" = "linearUp",
                  "Decreasing" = "linearDown"),selected="linearUp"), 
    p("Do the main and third factors work together or in opposition? Select one"),
    selectInput("shape13",label="Select response shape",c("Cooperative" = "coop",
                  "Opposing" = "oppo"),selected="coop"), 
    p("Do the second and third factors work together or in opposition?"),
    selectInput("shape23",label="Select interaction type",c("Cooperative" = "coop",
                  "Opposing" = "oppo"),selected="coop"), 				  
				  
	p("You can repeat as many simulations as you like by pressing the Simulate button"), 
    p(" "),
	h4(textOutput("effectText")),
	p(" "),
    actionButton("simExp",label="Simulate an experiment!"),
    p(" "),
    h4(textOutput("pValTextM")),
    p(" "),
    h4(textOutput("pValTextS")),
    p(" "),
    h4(textOutput("pValTextT")),
    p(" "),
    h4(textOutput("pValTextMS")),
    p(" "),
    h4(textOutput("pValTextMT")),
    p(" "),
    h4(textOutput("pValTextST")),
    p(" "),
    h4(textOutput("pValTextMST")),

    p(" "),
    p("The gray bars show the means from the two samples"),  
    p("The red dots show the simulated samples"),    
    textOutput("errorBarText"),
    plotOutput("distPlot")
    )
  )
))